\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{thesis}[2014/08/16 Example LaTeX class]

\LoadClass[]{scrartcl}
\usepackage{geometry}
\usepackage{abstract}
%\usepackage{draftwatermark}
%\SetWatermarkText{Draft}
%\SetWatermarkColor[gray]{0.5}
%\SetWatermarkLightness{0.8}
%\SetWatermarkScale{2}
\geometry{letterpaper, margin=1.5in}


\setkomafont{subtitle}{\normalfont\Large}



%\renewcommand{\normalsize}{\fontsize{11}{13}\selectfont}
