---
  - debug:
      msg: "{{ inventory_hostname }} has volumes {{ instance_volumes }}"
    when: instance_volumes is defined

  - name: Make ext4 filesystem on EBS volume
    command: mkfs -t ext4 {{ item.device_name }}
    with_items: "{{ instance_volumes }}"

  - name: Turn of journaling
    command: tune2fs -O {{ "^" }}has_journal {{ item.device_name }}
    with_items: "{{ instance_volumes }}"

  - name: Create mount point
    file: path=/mnt{{ item.device_name }} state=directory
    ignore_errors: yes
    with_items: "{{ instance_volumes }}"

  - name: Mount EBS volume at /mnt
    command: mount {{ item.device_name }} /mnt{{ item.device_name }}
    with_items: "{{ instance_volumes }}"
