---
# Install JDK 1.7 and perform other bootstrap tasks
- name: JDK | Oracle JDK | Make sure openjdk is uninstalled
  apt: pkg=openjdk-6-jdk state=absent

- name: JDK | Oracle JDK | Make sure openjdk is uninstalled
  apt: pkg=openjdk-7-jdk state=absent

- name: JDK | Oracle JDK | Make sure openjdk is uninstalled
  apt: pkg=openjdk-8-jdk state=absent

- name: JDK | Oracle JDK | Make a directory that holds the Java binaries
  file: path=/usr/local/java state=directory

- name: Add Oracles PPA
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Update APT cache
  apt: name=oracle-java8-installer update_cache=yes state=latest force=yes

- name: Setup TSC timer
  shell: echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource



