---
- name: Create EC2 instances for Zookeeper
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create Hadoop EC2 security group
      ec2_group:
        name: example
        description: an example EC2 group
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 10.0.0.0/8
          - proto: udp
            from_port: 10050
            to_port: 10050
            cidr_ip: 10.0.0.0/8
