---
- name: Create EC2 instances for Zookeeper
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Download JDK
      get_url: url={{ jdk_archive_url }} dest=/tmp/{{ jdk_archive_filename }} mode=0644 validate_certs=no headers='Cookie:oraclelicense=accept-securebackup-cookie'
