---
- name: get the username running the deploy
  command: whoami
  register: username_on_remote

- debug: var=username_on_remote

- name: Format namenode
  shell: "{{ common.soft_link_base_path }}/hadoop/bin/hdfs namenode -format"
  args:
    executable: /bin/bash

- name: Generate SSH key
  command: ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa

- name: Setup authorized keys
  shell: cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

- name: Setup known hosts
  shell: "ssh-keyscan {{ inventory_hostname }}  >> ~/.ssh/known_hosts"

- name: Setup known hosts
  shell: "ssh-keyscan 0.0.0.0 >> ~/.ssh/known_hosts"

- name: Setup known hosts
  shell: "ssh-keyscan 127.0.0.1  >> ~/.ssh/known_hosts"

- name: Setup known hosts
  shell: "ssh-keyscan {{ hostvars[inventory_hostname].private_ip }} >> ~/.ssh/known_hosts"

- name: Start HDFS services
  shell: "{{ common.soft_link_base_path }}/hadoop/sbin/start-dfs.sh"
  args:
    executable: /bin/bash

- name: Copy modified start-yarn.sh
  copy:
    src: "{{ role_path }}/sbin/start-yarn.sh"
    dest: "{{ common.soft_link_base_path }}/hadoop/sbin/start-yarn.sh"
    owner: "{{ hadoop.user }}"
    group: "{{ hadoop.group }}"
    mode: 0755

- name: Start YARN services
  shell: "{{ common.soft_link_base_path }}/hadoop/sbin/start-yarn.sh"
  args:
    executable: /bin/bash


- name: Wait for resourcemanager to come up
  wait_for: host=localhost port=8088 delay=60 timeout=360 state=started
